### ISSUE TITLE
Repo Query.Read()

### ISSUE THREAD

**Issue by thayavaran-m-incontact** [NiceLuc/Linq_Conversion_Tool#10]
Repo Query.Read() explicit conversion needed for (char,short,byte) types.

**Comment by NiceLuc** [comment]
This has been fixed in `Common`. I will get this merged into `API-CONT` branch shortly...

**Comment by NiceLuc** [comment]
Checked in change to `API-CONT` branch.

![image](https://github.com/user-attachments/assets/16bc085c-826a-4462-840a-1e8545ab21b0)
