### ISSUE TITLE
NonQuery DatabaseType

### ISSUE THREAD

**Issue by thayavaran-m-incontact** [NiceLuc/Linq_Conversion_Tool#11]
NonQuery DatabaseType created as IEnumerable  method.

ISingleResult is can be nonquery.

if (CurrentLine.Contains("ISingleResult"))
{
    method.DatabaseType = "Query";

    // todo: determine T vs. IEnumerable<T> for IsList
    method.IsList = true;
}
else
{
    method.DatabaseType = "NonQuery";

    // todo: determine void vs. return value for non-query calls
    // method.IsVoid = false;
}

**Comment by NiceLuc** [comment]
Reached out to @thayavaran-m-incontact for more information, and received this:

> For example Below is the Insert Method it's return type is ISingleResult, since it's return type is ISingleResult the tool is converting this method as IEnumerable but it should be int ExecuteNonQuery method.
 
```csharp
[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IC_InsertOrUpdateAssingFavoriteQuickReply")]
public ISingleResult<IC_InsertOrUpdateAssingFavoriteQuickReplyResult> IC_InsertOrUpdateAssingFavoriteQuickReply([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> Agent_No, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> QuickReplyId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> Bus_No, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> IsFavorite)
{
	IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), Agent_No, QuickReplyId, Bus_No, IsFavorite);
	return ((ISingleResult<IC_InsertOrUpdateAssingFavoriteQuickReplyResult>)(result.ReturnValue));
}
```
