### ISSUE TITLE
Repo Parameter

### ISSUE THREAD

**Issue by thayavaran-m-incontact** [NiceLuc/Linq_Conversion_Tool#9]
Parameter missing in repo conversion, Parameters which don't have name attribute.

[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IC_SelectScriptsByBusNo")]
public ISingleResult<IC_SelectScriptsByBusNoResult> IC_SelectScriptsByBusNo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> bus_no)
{
	IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bus_no);
	return ((ISingleResult<IC_SelectScriptsByBusNoResult>)(result.ReturnValue));
}

{
      "DatabaseName": "dbo.IC_SelectScriptsByBusNo",
      "DatabaseType": "Query",
      "MethodName": "IC_SelectScriptsByBusNo",
      "ReturnType": "IC_SelectScriptsByBusNoResult",
      "IsList": true,
      "HasReturnParameter": false,
      "Parameters": []
    },

**Comment by NiceLuc** [comment]
Ah, I see it. The fix will be to update the `ParametersParser.cs` file to fallback to the `net_name` reg ex match when the `db_name` match is missing:

```text
ParameterAttribute\((\s?Name\s?\=\s?""(?<db_name>.+?)"",)?\s?DbType\s?\=\s?""(?<db_type>.+?)"".+?]\s(?<ref_token>ref\s)?(?<net_type>.+?)\s(?<net_name>.+?)[,\)]
```

If the `db_name` is not found, we should instead use the `net_name` as the paramter value.
